# export SLACK_BOT_TOKEN=xoxb-213987454387-Que94Vj18hf3S9yIIHx5N8zy
# export SLACK_BOT_TOKEN=xoxb-214512466885-FzklYyL8SERwyFJbsbMHErFf
# export API_AI_TOKEN=679e6918cf1b4632b986f2c0994d88d3
export MONGODB_URI="mongodb://bot:Horizonites@ds163672.mlab.com:63672/schedule-bot-db"

export SLACK_BOT_TOKEN="xoxb-214512466885-FzklYyL8SERwyFJbsbMHErFf"
export API_AI_TOKEN="679e6918cf1b4632b986f2c0994d88d3"
export GOOGLE_CLIENT_ID="1098048398322-268dj4pv3m3oe9ccjj14dma60iue8lbp.apps.googleusercontent.com"
export GOOGLE_CLIENT_SECRET="gt6MHSZbOGf1CPBzFLrlztqR"
export DOMAIN="http://localhost:8080"

# { status: 200,
#   statusText: 'OK',
#   headers:
#    { server: 'nginx/1.11.9',
#      date: 'Tue, 18 Jul 2017 04:10:59 GMT',
#      'content-type': 'application/json;charset=UTF-8',
#      'content-length': '819',
#      'cache-control': 'no-cache, no-store, max-age=0, must-revalidate',
#      pragma: 'no-cache',
#      expires: '0',
#      'x-xss-protection': '1; mode=block',
#      'x-frame-options': 'DENY',
#      'x-content-type-options': 'nosniff',
#      'access-control-allow-credentials': 'true',
#      via: '1.1 google',
#      'alt-svc': 'clear',
#      connection: 'close' },
#   config:
#    { adapter: [Function: httpAdapter],
#      transformRequest: { '0': [Function: transformRequest] },
#      transformResponse: { '0': [Function: transformResponse] },
#      timeout: 0,
#      xsrfCookieName: 'XSRF-TOKEN',
#      xsrfHeaderName: 'X-XSRF-TOKEN',
#      maxContentLength: -1,
#      validateStatus: [Function: validateStatus],
#      headers:
#       { Accept: 'application/json, text/plain, */*',
#         Authorization: 'Bearer 679e6918cf1b4632b986f2c0994d88d3',
#         'User-Agent': 'axios/0.16.2' },
#      method: 'get',
#      params:
#       { v: 20150910,
#         query: 'remind me to pray tomorrow',
#         lang: 'en',
#         sessionId: 'U69RW1E82',
#         timezone: '2017-07-17T20:19:32-0700' },
#      url: 'https://api.api.ai/api/query',
#      data: undefined },
#   request:
#    ClientRequest {
#      domain: null,
#      _events:
#       { socket: [Function],
#         abort: [Function],
#         aborted: [Function],
#         error: [Function],
#         prefinish: [Function: requestOnPrefinish] },
#      _eventsCount: 5,
#      _maxListeners: undefined,
#      output: [],
#      outputEncodings: [],
#      outputCallbacks: [],
#      outputSize: 0,
#      writable: true,
#      _last: true,
#      upgrading: false,
#      chunkedEncoding: false,
#      shouldKeepAlive: false,
#      useChunkedEncodingByDefault: false,
#      sendDate: false,
#      _removedConnection: false,
#      _removedContLen: false,
#      _removedTE: false,
#      _contentLength: 0,
#      _hasBody: true,
#      _trailer: '',
#      finished: true,
#      _headerSent: true,
#      socket:
#       TLSSocket {
#         _tlsOptions: [Object],
#         _secureEstablished: true,
#         _securePending: false,
#         _newSessionPending: false,
#         _controlReleased: true,
#         _SNICallback: null,
#         servername: null,
#         npnProtocol: false,
#         alpnProtocol: false,
#         authorized: true,
#         authorizationError: null,
#         encrypted: true,
#         _events: [Object],
#         _eventsCount: 9,
#         connecting: false,
#         _hadError: false,
#         _handle: null,
#         _parent: null,
#         _host: 'api.api.ai',
#         _readableState: [Object],
#         readable: false,
#         domain: null,
#         _maxListeners: undefined,
#         _writableState: [Object],
#         writable: false,
#         allowHalfOpen: false,
#         _bytesDispatched: 295,
#         _sockname: null,
#         _pendingData: null,
#         _pendingEncoding: '',
#         server: undefined,
#         _server: null,
#         ssl: null,
#         _requestCert: true,
#         _rejectUnauthorized: true,
#         parser: null,
#         _httpMessage: [Circular],
#         read: [Function],
#         _consuming: true,
#         _idleNext: null,
#         _idlePrev: null,
#         _idleTimeout: -1,
#         [Symbol(asyncId)]: 93,
#         [Symbol(bytesRead)]: 1238 },
#      connection:
#       TLSSocket {
#         _tlsOptions: [Object],
#         _secureEstablished: true,
#         _securePending: false,
#         _newSessionPending: false,
#         _controlReleased: true,
#         _SNICallback: null,
#         servername: null,
#         npnProtocol: false,
#         alpnProtocol: false,
#         authorized: true,
#         authorizationError: null,
#         encrypted: true,
#         _events: [Object],
#         _eventsCount: 9,
#         connecting: false,
#         _hadError: false,
#         _handle: null,
#         _parent: null,
#         _host: 'api.api.ai',
#         _readableState: [Object],
#         readable: false,
#         domain: null,
#         _maxListeners: undefined,
#         _writableState: [Object],
#         writable: false,
#         allowHalfOpen: false,
#         _bytesDispatched: 295,
#         _sockname: null,
#         _pendingData: null,
#         _pendingEncoding: '',
#         server: undefined,
#         _server: null,
#         ssl: null,
#         _requestCert: true,
#         _rejectUnauthorized: true,
#         parser: null,
#         _httpMessage: [Circular],
#         read: [Function],
#         _consuming: true,
#         _idleNext: null,
#         _idlePrev: null,
#         _idleTimeout: -1,
#         [Symbol(asyncId)]: 93,
#         [Symbol(bytesRead)]: 1238 },
#      _header: 'GET /api/query?v=20150910&query=remind+me+to+pray+tomorrow&lang=en&sessionId=U69RW1E82&timezone=2017-07-17T20:19:32-0700 HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nAuthorization: Bearer 679e6918cf1b4632b986f2c0994d88d3\r\nUser-Agent: axios/0.16.2\r\nHost: api.api.ai\r\nConnection: close\r\n\r\n',
#      _onPendingData: [Function: noopPendingOutput],
#      agent:
#       Agent {
#         domain: null,
#         _events: [Object],
#         _eventsCount: 1,
#         _maxListeners: undefined,
#         defaultPort: 443,
#         protocol: 'https:',
#         options: [Object],
#         requests: {},
#         sockets: [Object],
#         freeSockets: {},
#         keepAliveMsecs: 1000,
#         keepAlive: false,
#         maxSockets: Infinity,
#         maxFreeSockets: 256,
#         maxCachedSessions: 100,
#         _sessionCache: [Object] },
#      socketPath: undefined,
#      timeout: undefined,
#      method: 'GET',
#      path: '/api/query?v=20150910&query=remind+me+to+pray+tomorrow&lang=en&sessionId=U69RW1E82&timezone=2017-07-17T20:19:32-0700',
#      _ended: true,
#      res:
#       IncomingMessage {
#         _readableState: [Object],
#         readable: false,
#         domain: null,
#         _events: [Object],
#         _eventsCount: 3,
#         _maxListeners: undefined,
#         socket: [Object],
#         connection: [Object],
#         httpVersionMajor: 1,
#         httpVersionMinor: 1,
#         httpVersion: '1.1',
#         complete: true,
#         headers: [Object],
#         rawHeaders: [Array],
#         trailers: {},
#         rawTrailers: [],
#         upgrade: false,
#         url: '',
#         method: null,
#         statusCode: 200,
#         statusMessage: 'OK',
#         client: [Object],
#         _consuming: true,
#         _dumped: false,
#         req: [Circular],
#         responseUrl: 'https://api.api.ai:443/api/query?v=20150910&query=remind+me+to+pray+tomorrow&lang=en&sessionId=U69RW1E82&timezone=2017-07-17T20:19:32-0700',
#         read: [Function] },
#      aborted: undefined,
#      timeoutCb: null,
#      upgradeOrConnect: false,
#      parser: null,
#      maxHeadersCount: null,
#      _redirectable:
#       Writable {
#         _writableState: [Object],
#         writable: true,
#         domain: null,
#         _events: [Object],
#         _eventsCount: 2,
#         _maxListeners: undefined,
#         _redirectCount: 0,
#         _onNativeResponse: [Function],
#         _currentRequest: [Circular],
#         _currentUrl: 'https://api.api.ai:443/api/query?v=20150910&query=remind+me+to+pray+tomorrow&lang=en&sessionId=U69RW1E82&timezone=2017-07-17T20:19:32-0700' },
#      [Symbol(outHeadersKey)]:
#       { accept: [Array],
#         authorization: [Array],
#         'user-agent': [Array],
#         host: [Array] } },
#   data:
#    { id: 'a2040588-2809-4135-80dc-82b265678b6f',
#      timestamp: '2017-07-18T04:10:59.729Z',
#      lang: 'en',
#      result:
#       { source: 'agent',
#         resolvedQuery: 'remind me to pray tomorrow',
#         action: '',
#         actionIncomplete: false,
#         parameters: [Object],
#         contexts: [],
#         metadata: [Object],
#         fulfillment: [Object],
#         score: 0.9100000262260437 },
#      status: { code: 200, errorType: 'success' },
#      sessionId: 'U69RW1E82' } }

# payload
# payload { actions: [ { name: 'confirm', type: 'button', value: 'true' } ],
#   callback_id: 'reminder',
#   team: { id: 'T6ANNBCTG', domain: 'teamexplodingkittens' },
#   channel: { id: 'D6B807LP8', name: 'directmessage' },
#   user: { id: 'U69RW1E82', name: 'decreaseme' },
#   action_ts: '1500414960.950425',
#   message_ts: '1500414950.257813',
#   attachment_id: '1',
#   token: 'XJXOiywK35EY1ObUJV6t16Gy',
#   is_app_unfurl: false,
#   original_message:
#    { text: 'Creating reminder for \'hi\' on 2017-07-18',
#      username: 'butler-bot-beta',
#      bot_id: 'B6A92T44T',
#      attachments: [ [Object] ],
#      type: 'message',
#      subtype: 'bot_message',
#      ts: '1500414950.257813' },
#   response_url: 'https://hooks.slack.com/actions/T6ANNBCTG/214459278579/yLf73yPdDadDBJ1w2OSc17vt' }
